using UnityEngine;

public class KeyAnimation : MonoBehaviour
{
    public float rotationSpeed = 50f;  // Velocidad de rotaci칩n
    public float floatAmplitude = 0.5f; // Altura m치xima de flotaci칩n
    public float floatSpeed = 2f;  // Velocidad de subida y bajada

    private Vector3 startPosition;

    void Start()
    {
        startPosition = transform.position;
    }

    void Update()
    {
        // Rotar sobre el eje Y
        transform.Rotate(Vector3.up * rotationSpeed * Time.deltaTime);

        // Movimiento de flotaci칩n en el eje Y
        float newY = startPosition.y + Mathf.Sin(Time.time * floatSpeed) * floatAmplitude;
        transform.position = new Vector3(transform.position.x, newY, transform.position.z);
    }
}
